import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import FormPresenter from "../components/FormPresenter";
import ResultPresenter from "../components/ResultPresenter";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [coordinates, setCoordinates] = useState<string[]>([]);

  const handleCoordinates = (inputLongitude: string, inputLatitude: string) => {
    setCoordinates([inputLongitude, inputLatitude]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>WeatherForecaster</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>WeatherForecaster</h1>

        <p className={styles.description}>
          Welcome to WeatherForecaster! To look for the weather at a particular
          location, please fill in the form below.
        </p>

        <FormPresenter handleCoordinates={handleCoordinates} />
        <ResultPresenter coordinates={coordinates} />
      </main>

      <footer className={styles.footer}>
        <p>Created by Jennifer Lindberg</p>
        <p>
          Powered by{" "}
          <a
            href="https://www.smhi.se/data/oppna-data/meteorologiska-data/api-for-vaderprognosdata-1.34233"
            target="_blank"
            rel="noreferrer"
          >
            SMHI API
          </a>
        </p>
      </footer>
    </div>
  );
};

export default Home;
